"""Known NetHack 3.6.7 facts checked against src/nh/data (generated by
scripts/gen_nh_data.py from the C sources).  Pure data -- no NLE needed.

test_generator_reproduces_data re-runs the generator when the 3.6.7 source
tree is present ($NH367_SRC or ~/src/nh367-data/NetHack-3.6.7)."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from nh.data.corpses import (  # noqa: E402
    Verdict,
    corpse_info,
    corpse_verdict,
    taint_chance,
)

DATA = SRC / "nh" / "data"


def _load(name: str) -> dict:
    return json.loads((DATA / name).read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def mons() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for m in _load("monsters.json")["monsters"]:
        out.setdefault(m["name"], m)  # were* names: first (animal) form
    return out


@pytest.fixture(scope="module")
def objs() -> dict[str, dict]:
    return {o["full_name"]: o for o in _load("objects.json")["objects"]
            if o["full_name"]}


HUMAN_VAL = dict(hero_race="human", hero_role="Valkyrie", has_poison_res=False)


# --- monsters.json ----------------------------------------------------------

def test_counts_match_a_stock_unix_build():
    m = _load("monsters.json")
    o = _load("objects.json")
    assert m["_meta"]["mail"] is True
    assert len(m["monsters"]) == m["_meta"]["count"] == 382  # NUMMONS
    assert len(o["objects"]) == o["_meta"]["count"] == 454   # NUM_OBJECTS
    assert [x["index"] for x in m["monsters"]] == list(range(382))


def test_newt_level_speed(mons):
    newt = mons["newt"]
    assert (newt["level"], newt["speed"], newt["ac"]) == (0, 6, 8)
    assert newt["symbol"] == ":" and newt["color"] == "yellow"


def test_jackal_and_soldier_ant_glyphs(mons):
    assert (mons["jackal"]["symbol"], mons["jackal"]["color"]) == ("d", "brown")
    assert mons["jackal"]["color_value"] == 3
    ant = mons["soldier ant"]
    assert (ant["symbol"], ant["color"], ant["color_value"]) == ("a", "blue", 4)
    assert [(a["type"], a["damage_type"], a["dice"]) for a in ant["attacks"]] == [
        ("AT_BITE", "AD_PHYS", "2d4"), ("AT_STNG", "AD_DRST", "3d4")]
    assert ant["geno"]["flags"] == ["G_SGROUP", "G_GENO"]
    assert ant["geno"]["frequency"] == 2


def test_flags_decoded(mons):
    eye = mons["floating eye"]
    assert "M1_NOLIMBS" in eye["flags1"] and "M1_FLY" in eye["flags1"]
    assert mons["cockatrice"]["resistances"] == ["MR_POISON", "MR_STONE"]
    assert "M2_UNDEAD" in mons["ghost"]["flags2"] and mons["ghost"]["symbol"] == " "
    assert "M2_PEACEFUL" in mons["shopkeeper"]["flags2"]
    assert mons["Medusa"]["geno"]["flags"] == ["G_UNIQ", "G_NOGEN"]
    assert mons["gnome king"]["sound"] == "MS_GRUNT"  # written MS_ORC in monst.c


def test_difficulty_matches_mstrength_port():
    for m in _load("monsters.json")["monsters"]:
        assert m["difficulty"] == m["difficulty_mstrength"], m["name"]


def test_difficulty_spot_values(mons):
    assert mons["jackal"]["difficulty"] == 1
    assert mons["soldier ant"]["difficulty"] == 6
    assert mons["mail daemon"]["difficulty"] == 26  # level 56 -> fixed-hp rule


# --- objects.json -----------------------------------------------------------

def test_object_facts(objs):
    ls = objs["long sword"]
    assert (ls["weapon"]["sdam"], ls["weapon"]["ldam"], ls["weapon"]["skill"]) == (
        8, 12, "P_LONG_SWORD")
    assert objs["plate mail"]["armor"] == {"ac": 7, "mc": 2, "category": "ARM_SUIT",
                                          "delay": 5, "bulky": True}
    assert objs["wand of striking"]["wand"]["direction"] == "IMMEDIATE"
    assert objs["wand of striking"]["appearance"] == "ebony"
    assert objs["spellbook of dig"]["material"] == "LEATHER"  # PAPER->LEATHER hack
    assert objs["spellbook of dig"]["spellbook"]["level"] == 5
    assert objs["unicorn horn"]["weapon"]["to_hit"] == 1  # WEPTOOL(PIERCE) quirk
    assert objs["food ration"]["food"] == {"nutrition": 800, "delay": 5}
    assert objs["elven arrow"]["unidentified_name"] == "runed arrow"
    assert objs["arrow"]["weapon"]["kind"] == "ammo"


def test_probabilities_sum_to_1000_per_class():
    sums: dict[str, int] = {}
    for o in _load("objects.json")["objects"]:
        sums[o["class"]] = sums.get(o["class"], 0) + o["prob"]
    assert sums["POTION_CLASS"] == sums["WEAPON_CLASS"] == sums["GEM_CLASS"] == 1000
    assert all(s in (0, 1000) for s in sums.values())


def test_shuffle_groups():
    groups = _load("objects.json")["shuffle_groups"]
    assert "potion of water" not in groups["potion"]["names"]
    assert len(groups["scroll"]["appearances"]) == 41  # 21 scrolls + 20 labels
    assert len(groups["wand"]["names"]) == 24 and len(groups["wand"]["appearances"]) == 27
    assert groups["boots"]["materials_shuffled"] is False
    assert "pair of speed boots" in groups["boots"]["names"]


# --- glyph_index.json / features.json ----------------------------------------

def test_glyph_index():
    g = _load("glyph_index.json")
    assert "jackal" in g["monsters"]["d|3"]
    assert g["monsters"]["a|4"] == ["soldier ant"]
    assert "floating eye" in g["monsters"]["e|4"]
    assert "lichen" in g["corpses"]["%|10"]          # corpse drawn in monster colour
    assert "jackal" in g["statues"]["d|15"]          # statues: letter in white
    assert {"appearance": "ruby", "unidentified_name": "ruby potion",
            "shuffle_group": "potion"} in g["objects"]["!|1"]
    assert g["objects"]["`|7"] == [{"name": "boulder"}]
    assert "S_fountain" in g["features"]["{|12"]


def test_features():
    f = _load("features.json")
    by_id = {c["id"]: c for c in f["cmap"]}
    expect = {"S_fountain": ("{", "bright_blue"), "S_altar": ("_", "gray"),
              "S_throne": ("\\", "yellow"), "S_sink": ("#", "gray"),
              "S_grave": ("|", "white"), "S_tree": ("#", "green"),
              "S_pool": ("}", "blue"), "S_lava": ("}", "red"),
              "S_ice": (".", "cyan"), "S_bars": ("#", "cyan"),
              "S_vcdoor": ("+", "brown"), "S_upstair": ("<", "gray")}
    for sid, (ch, col) in expect.items():
        assert (by_id[sid]["char"], by_id[sid]["color"]) == (ch, col), sid
    traps = {t["id"]: t for t in f["traps"]}
    assert len(traps) == 23
    assert (traps["MAGIC_PORTAL"]["char"], traps["MAGIC_PORTAL"]["color"]) == (
        "^", "bright_magenta")
    assert traps["WEB"]["char"] == '"'
    assert f["other_symbols"]["boulder"]["char"] == "`"


# --- corpses.py ---------------------------------------------------------------

def test_floating_eye_conveys_telepathy():
    assert corpse_info("floating eye")["intrinsics"] == {"telepathy": 1.0}
    v = corpse_verdict("floating eye", age_turns=5, **HUMAN_VAL)
    assert v.verdict is Verdict.SAFE
    assert "telepathy: certain" in v.benefits


def test_cockatrice_is_never():
    v = corpse_verdict("cockatrice", age_turns=1, **HUMAN_VAL)
    assert v.verdict is Verdict.NEVER
    assert corpse_verdict("chickatrice corpse", age_turns=1, **HUMAN_VAL).verdict \
        is Verdict.NEVER
    assert corpse_verdict("Medusa's corpse", age_turns=1, **HUMAN_VAL).verdict \
        is Verdict.NEVER
    safe = corpse_verdict("cockatrice", age_turns=1, has_stoning_res=True,
                          **HUMAN_VAL)
    assert safe.verdict is Verdict.SAFE


def test_lichen_and_lizard_never_rot():
    for name in ("lichen", "lizard"):
        assert corpse_info(name)["never_rots"]
        v = corpse_verdict(name, age_turns=50000, **HUMAN_VAL)
        assert v.verdict is Verdict.SAFE and v.taint_chance == 0.0
    assert corpse_info("lizard")["cures_stoning"]


def test_rotting_thresholds():
    assert taint_chance(59) == 0.0
    assert taint_chance(60) == 0.05          # only the /10 divisor
    assert taint_chance(174) == 1.0          # 174 // 29 == 6
    assert taint_chance(40, "cursed") > 0    # cursed: +2 rotted
    assert taint_chance(79, "blessed") == 0.0
    assert corpse_verdict("jackal", age_turns=10, **HUMAN_VAL).verdict is Verdict.SAFE
    assert corpse_verdict("jackal", age_turns=200, **HUMAN_VAL).verdict is Verdict.DEADLY
    # acid blobs are exempt from tainting
    old_blob = corpse_verdict("acid blob", age_turns=5000, **HUMAN_VAL)
    assert old_blob.taint_chance == 0.0 and old_blob.verdict is Verdict.RISKY
    # zombie corpses start 100 turns old: 35% tainted even when fresh
    z = corpse_verdict("kobold zombie", age_turns=0, **HUMAN_VAL)
    assert z.monster == "kobold" and z.taint_chance == pytest.approx(0.35)


def test_poison_and_acid():
    assert corpse_verdict("kobold", age_turns=1, **HUMAN_VAL).verdict is Verdict.RISKY
    resist = dict(HUMAN_VAL, has_poison_res=True)
    assert corpse_verdict("kobold", age_turns=1, **resist).verdict is Verdict.SAFE
    bee = corpse_info("killer bee")["intrinsics"]["poison resistance"]
    assert bee == pytest.approx(0.25 + 0.75 / 15)  # givit() special case


def test_lycanthropy_either_form():
    for name in ("werejackal", "PM_WEREJACKAL", "PM_HUMAN_WEREWOLF"):
        v = corpse_verdict(name, age_turns=1, hero_race="orc", hero_role="Rogue",
                           has_poison_res=True)
        assert v.verdict is Verdict.NEVER
        assert any("lycanthropy" in r for r in v.reasons)


def test_cannibalism_and_pets():
    assert corpse_verdict("human", age_turns=1, **HUMAN_VAL).verdict is Verdict.NEVER
    assert corpse_verdict("human", age_turns=1, hero_race="orc", hero_role="Barbarian",
                          has_poison_res=False).verdict is Verdict.SAFE
    dwarf_cav = dict(hero_race="dwarf", hero_role="Caveman", has_poison_res=False)
    assert corpse_verdict("dwarf", age_turns=1, **dwarf_cav).verdict is Verdict.SAFE
    assert corpse_verdict("Woodland-elf", age_turns=1, hero_race="elf",
                          hero_role="Wizard", has_poison_res=False).verdict \
        is Verdict.NEVER
    assert corpse_verdict("little dog", age_turns=1, **HUMAN_VAL).verdict is Verdict.NEVER
    assert corpse_verdict("little dog", age_turns=1, **dwarf_cav).verdict is Verdict.SAFE


def test_special_corpses():
    assert corpse_verdict("Death", age_turns=1, **HUMAN_VAL).verdict is Verdict.NEVER
    assert corpse_verdict("glob of green slime", age_turns=1, **HUMAN_VAL).verdict \
        is Verdict.NEVER
    assert corpse_info("bat")["stun_turns"] == 30
    assert corpse_info("violet fungus")["hallucination_turns"] == 200
    assert corpse_info("chameleon")["polymorph"]
    assert corpse_info("hill giant")["strength_chance"] == 0.5
    assert corpse_info("quantum mechanic")["intrinsics"] == {}  # no givit() roll
    assert corpse_info("wraith")["gain_level"]
    sat = corpse_verdict("newt", age_turns=1, is_satiated=True, **HUMAN_VAL)
    assert sat.verdict is Verdict.DEADLY  # choking


# --- reproducibility ----------------------------------------------------------

def test_generator_reproduces_data(tmp_path):
    src = Path(os.environ.get("NH367_SRC",
                              Path.home() / "src" / "nh367-data" / "NetHack-3.6.7"))
    if not (src / "src" / "monst.c").is_file():
        pytest.skip("NetHack 3.6.7 source tree not available")
    subprocess.run([sys.executable, str(REPO / "scripts" / "gen_nh_data.py"),
                    str(src), "--out", str(tmp_path)], check=True,
                   capture_output=True)
    for name in ("monsters.json", "objects.json", "glyph_index.json",
                 "features.json"):
        assert (tmp_path / name).read_bytes() == (DATA / name).read_bytes(), name
